### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by anhk** [007pig/plugin-jieba#4]
# gitbook serve --port 80

Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 12 plugins are installed 
info: 7 explicitly listed 
info: loading plugin "prism"... OK 
info: loading plugin "toggle-chapters"... OK 
info: loading plugin "search-pro"... OK 
info: loading plugin "livereload"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-comscore"... OK 
info: loading plugin "theme-default"... OK 
info: found 83 pages 
info: found 14 asset files 
warn: "options" property is deprecated, use config.get(key) instead 
init!
warn: "page.progress" property is deprecated 

TypeError: Arguments to path.join must be strings

**Comment by zilan920** [comment]
I am having the same problem, it seems like you have fixed it ,can you tell me how? thanks
